### ISSUE TITLE
Clean up the ``THIRD-PARTY.properties`` files

### ISSUE THREAD

**Issue by nuest** [52North/WPS#211]
There is a bunch of probably automatically generated files ``<module>/src/license/THIRD-PARTY.properties``. Maybe these can be removed?

To me it looks like they were automatically generated by a license plugin.

Examples:

* https://github.com/52North/WPS/blob/wps-4.0/52n-wps-r/src/license/THIRD-PARTY.properties
* https://github.com/52North/WPS/blob/wps-4.0/52n-wps-mc/src/license/THIRD-PARTY.properties

**Comment by matthesrieke** [comment]
yes, most likely not required.
