### ISSUE TITLE
ExecutionContext.getTempDirectoryPath() misses to put an "/" after the java.io.tmpdir property

### ISSUE THREAD

**Issue by grmpfhmbl** [52North/WPS#228]
Not sure, if this is a bug in WPS or my Java environment is poorly configured, but `ExecutionContext.getTempDirectoryPath()` returns _/var/tmp3a5d1d23-50db-4a9e-ade0-b741e1fade09_" and I guess it should return _/var/tmp/3a5d1d23-50db-4a9e-ade0-b741e1fade09_

If that is a but, I'd fix it by changing Line 47 to

        return System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + this.tempFolderName;

and create a pull request.

**Comment by bpross-52n** [comment]
Thanks for this, it seems to be a bug. We would be glad, if you would contribute a fix. Note that we will need a signed Contributors Licence Agreement from you before we can accept a possible PR. You can find more info here: http://52north.org/about/licensing/cla-guidelines

**Comment by grmpfhmbl** [comment]
@bpross-52n I just created a PR. The signed CLA should hopefully arrive in the next couple of days at 52° North.
