### ISSUE TITLE
How to setup 52°North WPS with GRASS backend under Windows and Linux

### ISSUE THREAD

**Issue by houzw** [52North/WPS#265]
I followed tutorials [TutorialBackendGRASSWin](https://wiki.52north.org/Geoprocessing/TutorialBackendGRASSWin) and [TutorialBackendWpsGRASSLinux](https://wiki.52north.org/Geoprocessing/TutorialBackendWpsGRASSLinux) to setup 52°North WPS with GRASS backend under Windows and Linux (CentOS 7), but result of GetCapabilities request does not contain any GRASS algorithms.

My configuration under windows  is
```
GISRC_Dir   D:\Program Files\GRASS GIS 7.2.0\.grassrc72
Grass_Home  D:\Program Files\GRASS GIS 7.2.0
ModuleStarter_Home   D:\Programs\wps-grass-bridge\gms
Python_Home   D:\Program Files\Python2.7.9
Python_Path   D:\Program Files\Python2.7.9
TMP_Dir  D:\Programs\tmp\grass_tmp
```
and under linux:
```
GISRC_Dir   /home/houzw/.grass7/rc
Grass_Home  /usr/lib64/grass74
ModuleStarter_Home  /opt/soft/wps-grass-bridge/gms/
Python_Home  /usr/bin/
Python_Path   /usr/bin/python2.7
TMP_Dir  /home/houzw/tmp/grass_tmp
```
Any suggestions? Thanks

**Comment by bpross-52n** [comment]
I just tested the GRASS backend on windows. Seems to work for me. What version of the WPS are you using?

**Comment by houzw** [comment]
I have found the problem:
In webadmin page `index.jsp`, width of checkbox to activate algoritms repository is set to 0, so that is impossible to active the repository 
the version of wps is 3.6.1
